---
title: "The Statistical Reinforcement Learning Lab"
---

The [Statistical Reinforcement Learning Lab](http://dept.stat.lsa.umich.edu/~samurphy/nida/overview.html) (SRLL) is a research lab at the University of Michigan (UM) Ann Arbor. 

The research team is particulary interested in the field of mobile health. The research focus is on combining statistical inference methods (confidence intervals, hypothesis testing) with algorithmic methods developed in computer science for use in reinforcement learning and evaluating treatment policies (adaptive interventions and just-in-time adaptive interventions in mobile health)


## Undergraduates


This lab is a great foundation for undergraduates of statistics, computer science, and data science who are seeking research experience and or looking into pursuing a graduate degree in statistics or a related field.


To learn more about the lab, check out the [Interested?](https://tahmeed14.github.io/srll_undergrads/about.html) tab


## E-Meet Them

### [Michael Kovalcik](https://sites.google.com/a/umich.edu/michael_kovalcik/home)

- Major: Computer Science Engineering
- Research:
- Campus Involvement: [Michigan Data Science Team](http://midas.umich.edu/mdst/)
- Email: 

### [Katherine Li]()

- Major: Statistics and Economics
- Research: [SARA](https://tahmeed14.github.io/srll_undergrads/about.html)
- Campus Involvement:
- Email:

### [Tahmeed Tureen](https://sites.google.com/a/umich.edu/tahmeed-tureen/)

- Major: Statistics
- Research: 
- Campus Involvement: [Michigan Undergraduate Students of Statistics (Mugss)](https://maizepages.umich.edu/organization/mugss), [SI 506: Programming I](https://www.si.umich.edu/programs/courses/506) Instructional Aide, [Michigan Club Lacrosse](https://www.michiganclublacrosse.com/)
- Email: tureen@umich.edu


## Former Undergraduates

- [Kelly Hall](https://sites.google.com/a/umich.edu/kellyhall/)
- Xi Chen

If you are interested about learning more about the specifics of research and what we do check out the [Interested?](https://tahmeed14.github.io/srll_undergrads/about.html) page.
